FROM node:lts as base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app
COPY .env ./.env
COPY public ./public
COPY src ./src
COPY prisma ./prisma
COPY *.js ./
COPY *.json ./
COPY pnpm-lock.yaml ./

FROM base AS build
WORKDIR /app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run build

FROM base
WORKDIR /app

ENV NODE_ENV production

COPY --from=build /app/.env ./
COPY --from=build /app/next.config.js ./
COPY --from=build /app/google.json ./
COPY --from=build /app/public ./public
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static

EXPOSE 3000

CMD ["sh", "-c", "node server.js"]
