name: Lint Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'pnpm'
          
      - name: Lint
        run: |
          pnpm install
          pnpm run lint                              

      - name: Notify
        uses: teknatha136/actions-google-chat-text-message@main
        with:
          google-chat-webhook: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          text-message: "Smartskills Lint Checks <https://git.s4.smartdata.solutions/${{ gitea.repository }}/actions/runs/${{ gitea.run_number }}|#${{ gitea.run_number }}> for branch *${{ gitea.head_ref || gitea.ref_name }}*, *${{ gitea.event_name }}* by *${{ gitea.actor }}*\nStatus: *${{ job.status }}*"
        if: always()