export const POSITIONS = [
  { title: "Founder" },
  { title: "CEO" },
  { title: "CTO" },
  { title: "Front End Developer" },
  { title: "Back End Developer" },
  { title: "Fullstack Developer" },
  {
    title: "Quality Assurance Engineer",
  },
  { title: "Project Manager" },
  { title: "Data Scientist" },
  { title: "Mobile Developer" },
  { title: "Chief Accountant" },
  { title: "Human Resource Manager" },
  { title: "Devops Engineer" },
  { title: "Recruiter" },
  { title: "Machine Learning Engineer" },
  { title: "Head of Frontend Department" },
  { title: "Head of Backend Department" },
];

export const TECHNOLOGIES = [
  { title: "ReactJs" },
  { title: "NextJs" },
  { title: "VueJs" },
  { title: "JavaScript" },
  { title: "PHP" },
  { title: "CSS" },
  { title: "Java" },
  { title: "Laravel" },
  { title: "Python" },
  { title: "Machine Learning" },
  { title: "ExpressJs" },
  { title: "NodeJs" },
  { title: "MySQL" },
  { title: "PostgreSQL" },
  { title: "Jira" },
  { title: "Redux" },
  { title: "Yup" },
  { title: "React-hook-form" },
  { title: "Project Manager" },
  { title: "Quality Assurance" },
  { title: "tRPC" },
  { title: "User Experience" },
  { title: "User Interface" },
  { title: "WordPress" },
];
