export const USER_POSITION = [
  { value: "Founder", label: "Founder" },
  { value: "CEO", label: "CEO" },
  { value: "CTO", label: "CTO" },
  { value: "Front End Developer", label: "Front End Developer" },
  { value: "Back End Developer", label: "Back End Developer" },
  { value: "Fullstack Developer", label: "Fullstack Developer" },
  {
    value: "Quality Assurance Specialist",
    label: "Quality Assurance Specialist",
  },
  { value: "Project Manager", label: "Project Manager" },
  { value: "Data Scientist", label: "Data Scientist" },
  { value: "Mobile Developer", label: "Mobile Developer" },
  { value: "Chief Accountant", label: "Chief Accountant" },

  { value: "Human Resource Specilist", label: "Human Resource Specialist" },
];

export const TECHNOLOGIES = [
  { value: "ReactJs", label: "ReactJs" },
  { value: "NextJs", label: "NextJs" },
  { value: "VueJs", label: "VueJs" },
  { value: "JavaScript", label: "JavaScript" },
  { value: "PHP", label: "PHP" },
  { value: "CSS", label: "CSS" },
  { value: "Java", label: "Java" },
  { value: "Laravel", label: "Laravel" },
  { value: "NestJs", label: "NestJs" },
  { value: "Python", label: "Python" },
  { value: "Machine Learning", label: "Machine Learning" },
  { value: "Project Manager", label: "Machine Learning" },
  { value: "ExpressJs", label: "ExpressJs" },
  { value: "NodeJs", label: "NodeJs" },
  { value: "MySQL", label: "MySQL" },
  { value: "PostgreSQL", label: "PostgreSQL" },
  { value: "Jira", label: "Jira" },
  { value: "Redux", label: "Redux" },
  { value: "Yup", label: "Yup" },
  { value: "React-hook-form", label: "React-hook-form" },
];
