export const POSITIONS = [
  { title: "Founder" },
  { title: "CEO" },
  { title: "CTO" },
  { title: "Front End Developer" },
  { title: "Back End Developer" },
  { title: "Fullstack Developer" },
  {
    title: "Quality Assurance Specialist",
  },
  { title: "Project Manager" },
  { title: "Data Scientist" },
  { title: "Mobile Developer" },
  { title: "Chief Accountant" },

  { title: "Human Resource Specialist" },
];

export const TECHNOLOGIES = [
  { title: "ReactJs", authorId: "" },
  // { value: "ReactJs", label: "ReactJs" },
  // { value: "NextJs", label: "NextJs" },
  // { value: "VueJs", label: "VueJs" },
  // { value: "JavaScript", label: "JavaScript" },
  // { value: "PHP", label: "PHP" },
  // { value: "CSS", label: "CSS" },
  // { value: "Java", label: "Java" },
  // { value: "Laravel", label: "Laravel" },
  // { value: "NestJs", label: "NestJs" },
  // { value: "Python", label: "Python" },
  // { value: "Machine Learning", label: "Machine Learning" },
  // { value: "Project Manager", label: "Machine Learning" },
  // { value: "ExpressJs", label: "ExpressJs" },
  // { value: "NodeJs", label: "NodeJs" },
  // { value: "MySQL", label: "MySQL" },
  // { value: "PostgreSQL", label: "PostgreSQL" },
  // { value: "Jira", label: "Jira" },
  // { value: "Redux", label: "Redux" },
  // { value: "Yup", label: "Yup" },
  // { value: "React-hook-form", label: "React-hook-form" },
];
